# Generated by Django 2.1.7 on 2019-04-15 13:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0003_auto_20190401_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='page1.Theme', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(5, message='ERROR!')]),
        ),
    ]
