version: '3'

services:

  app:
    build:
      context: .
    command: python ps_app.py
    ports:
      - 5000:5000
    env_file:
      - app/.env
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    env_file:
      - app/.env
    restart: always